//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_trip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wpt
    {
        public int wpt_id { get; set; }
        public string wpt_name { get; set; }
        public string wpt_description { get; set; }
        public string wpt_date_creation { get; set; }
        public string  wpt_coordinate { get; set; }
    }
}
